--- #YAML:1.0
name:                POSIX-Regex
version:             0.90.11
abstract:            ~
license:             ~
author:              
    - Paul Miller <jettero@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    ExtUtils::Constant:            0.16
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
