---
name: POSIX-Regex
version: 0.90.15
author:
  - 'Jettero Heller <japh@voltar-confed.org>'
abstract: OO interface for the gnu regex engine
license: lgpl
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  version: 0
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::Constant: 0
provides:
  POSIX::Regex:
    file: Regex.pm
    version: 0.90.15
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
